name       : soapyrtlsdr
version    : 0.3.0
release    : 3
source     :
    - https://github.com/pothosware/SoapyRTLSDR/archive/soapy-rtlsdr-0.3.0.tar.gz : 9c31c67c2646628b448bbef1307f3880b7e78be8caf7a02cd3cfa4d08dc4075b
license    : MIT
component  : programming.library
summary    : SoapySDR RTL-SDR Support Module
description: |
    Soapy SDR module for RTL-SDR
builddeps  :
    - pkgconfig(SoapySDR)
    - pkgconfig(librtlsdr)
setup      : |
    %cmake . -DLIB_SUFFIX=64
build      : |
    %make
install    : |
    %make_install
