name       : soapyrtlsdr
version    : 0.2.4
release    : 1
source     :
    - https://github.com/pothosware/SoapyRTLSDR/archive/soapy-rtlsdr-0.2.4.tar.gz : b034025d5c9ced8a371511cb8b14dc841996477f86387a4ebd58d0e71747db59
license    : MIT
component  : programming.library
summary    : SoapySDR RTL-SDR Support Module
description: |
    Soapy SDR module for RTL-SDR
builddeps  :
    - pkgconfig(librtlsdr)
    - pkgconfig(SoapySDR)
setup      : |
    %cmake . -DLIB_SUFFIX=64
build      : |
    %make
install    : |
    %make_install
